[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nba_pbp"
version = "0.1.0"
description = "NBA play-by-play analysis package"
readme = "README.md"
authors = [{name="Henry Holt"}]
license = { file = "LICENSE" }
dependencies = ["pandas"]

[tool.setuptools.packages.find]
include = ["nba_pbp*"]
